"""Schemas for video upload API responses."""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class VideoUploadResponse(BaseModel):
    """Metadata returned after an upload is safely stored."""

    id: str = Field(description="Unique identifier generated by the server")
    original_filename: str
    stored_filename: str
    content_type: str
    size_bytes: int = Field(ge=1)
    status: Literal["uploaded"]
    safety_notice: str


class VideoProcessingResponse(BaseModel):
    """Technical metadata for a completed OpenCV processing run."""

    id: str
    status: Literal["completed"]
    processed_filename: str
    frame_count: int = Field(ge=1)
    width: int = Field(ge=1)
    height: int = Field(ge=1)
    fps: float = Field(gt=0)
    duration_seconds: float = Field(ge=0)
    detection_mode: Literal["mock", "yolo"]
    total_person_detections: int = Field(ge=0)
    frames_with_people: int = Field(ge=0)
    unique_people_tracked: int = Field(ge=0)
    maximum_inactivity_seconds: float = Field(ge=0)
    maximum_risk_score: float = Field(ge=0, le=100)
    danger_frame_count: int = Field(ge=0)
    pose_mode: Literal["disabled", "yolo"]
    pose_frames_analyzed: int = Field(ge=0)
    incident_count: int = Field(ge=0)
    incidents: list["IncidentSummary"]
    download_url: str


class IncidentSummary(BaseModel):
    """Small incident representation returned after video processing."""

    id: str
    track_id: int
    risk_score: float
    occurred_at_seconds: float
    status: str
    snapshot_url: str
    clip_url: str
    created_at: datetime


class IncidentActionResponse(BaseModel):
    """Incident status returned after an operator action."""

    id: str
    status: Literal["unresolved", "acknowledged", "resolved", "false_alarm"]


class ProcessingJobCreated(BaseModel):
    """Identifiers returned as soon as a background job starts."""

    job_id: str
    video_id: str
    status: Literal["queued", "processing"]


class ProcessingProgressMessage(BaseModel):
    """Message sent repeatedly through the processing WebSocket."""

    job_id: str
    status: Literal["queued", "processing", "completed", "failed"]
    progress: float = Field(ge=0, le=100)
    error: str | None = None
    result: VideoProcessingResponse | None = None
